language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
matrix:
  include:
    - perl: "5.20"
      env: COVERAGE=1 PERL_MM_USE_DEFAULT=1 NONINTERACTIVE_TESTING=1
      before_install:
        - cpanm --quiet --notest Devel::Cover::Report::Coveralls
        - cpanm --quiet --notest .
      script: "perl Build.PL --extra-compiler-flags \"-O0 --coverage\" --extra-linker-flags \"--coverage\" && ./Build && cover -test -report coveralls -ignore_re /CORE/\\w+\\.h$"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
sudo: false
