---
abstract: 'Fast IP-address to country-code translation using multiple databases'
author:
  - 'Craig MacKenna <craig@animalhead.com>'
build_requires:
  ExtUtils::CBuilder: 0
  File::Copy: 0
  Probe::Perl: 0
  Test::More: 0
configure_requires:
  Config: 0
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IP-World
provides:
  IP::World:
    file: lib/IP/World.pm
    version: 0.17
requires:
  Carp: 0
  File::ShareDir: 0
  HTTP::Status: 0
  LWP::UserAgent: 0
  Time::HiRes: 0
  perl: v5.7.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.17
